#ifndef MACHINE2_H_
#define MACHINE2_H_

#include "symbols.h"

/*
 * The complete transition table for the Turing machine.
 * All un-filled rules will default to {0, 0, STATE_ERROR}
 * because STATE_ERROR is 0.
 */
static const Transition g_transition_table[NUM_STATES][NUM_SYMBOLS] = {

	/* --- STATE_HALT / STATE_ERROR: (No transitions) --- */
	[STATE_ERROR] = {
		[SYM_PERIOD] = {SYM_PERIOD, 0, STATE_ERROR},
		[SYM_HASH]   = {SYM_HASH,   0, STATE_ERROR},
		[SYM_X]      = {SYM_X,      0, STATE_ERROR},
		[SYM_R]      = {SYM_R,      0, STATE_ERROR},
		[SYM_AT]     = {SYM_AT,     0, STATE_ERROR},
		[SYM_T]      = {SYM_T,      0, STATE_ERROR},
		[SYM_E]      = {SYM_E,      0, STATE_ERROR},
		[SYM_SH_PERIOD] = {SYM_SH_PERIOD, 0, STATE_ERROR},
		[SYM_SH_HASH]   = {SYM_SH_HASH,   0, STATE_ERROR},
		[SYM_SH_X]      = {SYM_SH_X,      0, STATE_ERROR},
		[SYM_SH_R]      = {SYM_SH_R,      0, STATE_ERROR},
	},
	[STATE_HALT] = {
		[SYM_PERIOD] = {SYM_PERIOD, 0, STATE_HALT},
		[SYM_HASH]   = {SYM_HASH,   0, STATE_HALT},
		[SYM_X]      = {SYM_X,      0, STATE_HALT},
		[SYM_R]      = {SYM_R,      0, STATE_HALT},
		[SYM_AT]     = {SYM_AT,     0, STATE_HALT},
		[SYM_T]      = {SYM_T,      0, STATE_HALT},
		[SYM_E]      = {SYM_E,      0, STATE_HALT},
		[SYM_SH_PERIOD] = {SYM_SH_PERIOD, 0, STATE_HALT},
		[SYM_SH_HASH]   = {SYM_SH_HASH,   0, STATE_HALT},
		[SYM_SH_X]      = {SYM_SH_X,      0, STATE_HALT},
		[SYM_SH_R]      = {SYM_SH_R,      0, STATE_HALT},
	},

	/* --- 1. MAIN 8-STATE LOGIC --- */
	
	[STATE_QUERY_UP] = {
		[SYM_PERIOD] = {SYM_SH_PERIOD, -1, STATE_GOTO_HOME_UP},
		[SYM_HASH]   = {SYM_SH_HASH,   -1, STATE_GOTO_HOME_UP},
		[SYM_X]      = {SYM_SH_X,      -1, STATE_GOTO_HOME_UP},
		/* R is a valid grid cell to be on, but shouldn't be */
	},
	[STATE_QUERY_RIGHT] = {
		[SYM_PERIOD] = {SYM_X, +1, STATE_RESPOND_RIGHT},
		[SYM_X]      = {SYM_X, +1, STATE_RESPOND_RIGHT},
	},
	[STATE_QUERY_DOWN] = {
		[SYM_PERIOD] = {SYM_SH_PERIOD, -1, STATE_GOTO_HOME_DOWN},
		[SYM_HASH]   = {SYM_SH_HASH,   -1, STATE_GOTO_HOME_DOWN},
		[SYM_X]      = {SYM_SH_X,      -1, STATE_GOTO_HOME_DOWN},
	},
	[STATE_QUERY_LEFT] = {
		[SYM_PERIOD] = {SYM_X, -1, STATE_RESPOND_LEFT},
		[SYM_X]      = {SYM_X, -1, STATE_RESPOND_LEFT},
	},
	
	[STATE_RESPOND_UP] = {
		[SYM_PERIOD] = {SYM_X, 0, STATE_QUERY_UP},
		[SYM_X]      = {SYM_X, 0, STATE_QUERY_UP},
		[SYM_HASH]   = {SYM_SH_HASH, -1, STATE_GOTO_HOME_DOWN_RETURN},
		[SYM_R]      = {SYM_R, 0, STATE_HALT}, /* Explicitly halt on R */
	},
	[STATE_RESPOND_RIGHT] = {
		[SYM_PERIOD] = {SYM_X, 0, STATE_QUERY_RIGHT},
		[SYM_X]      = {SYM_X, 0, STATE_QUERY_RIGHT},
		[SYM_HASH]   = {SYM_HASH, -1, STATE_QUERY_DOWN},
		[SYM_R]      = {SYM_R, 0, STATE_HALT}, /* Explicitly halt on R */
	},
	[STATE_RESPOND_DOWN] = {
		[SYM_PERIOD] = {SYM_X, 0, STATE_QUERY_DOWN},
		[SYM_X]      = {SYM_X, 0, STATE_QUERY_DOWN},
		[SYM_HASH]   = {SYM_SH_HASH, -1, STATE_GOTO_HOME_UP_RETURN},
		[SYM_R]      = {SYM_R, 0, STATE_HALT}, /* Explicitly halt on R */
	},
	[STATE_RESPOND_LEFT] = {
		[SYM_PERIOD] = {SYM_X, 0, STATE_QUERY_LEFT},
		[SYM_X]      = {SYM_X, 0, STATE_QUERY_LEFT},
		[SYM_HASH]   = {SYM_HASH, +1, STATE_QUERY_UP},
		[SYM_R]      = {SYM_R, 0, STATE_HALT}, /* Explicitly halt on R */
	},

/* Macro to fill all symbols for a "commute" state */
#define COMMUTE_RULE(move_dir, next_state, beacon_sym, beacon_move, beacon_next) \
	[SYM_PERIOD] = {SYM_PERIOD, move_dir, next_state}, \
	[SYM_HASH]   = {SYM_HASH,   move_dir, next_state}, \
	[SYM_X]      = {SYM_X,      move_dir, next_state}, \
	[SYM_R]      = {SYM_R,      move_dir, next_state}, \
	[SYM_T]      = {SYM_T,      move_dir, next_state}, \
	[SYM_E]      = {SYM_E,      move_dir, next_state}, \
	[SYM_SH_PERIOD] = {SYM_SH_PERIOD, move_dir, next_state}, \
	[SYM_SH_HASH]   = {SYM_SH_HASH,   move_dir, next_state}, \
	[SYM_SH_X]      = {SYM_SH_X,      move_dir, next_state}, \
	[SYM_SH_R]      = {SYM_SH_R,      move_dir, next_state}, \
	[beacon_sym] = {beacon_sym, beacon_move, beacon_next}

	/* --- 2. SUBROUTINE: GO_UP (pos - NCOLS) --- */
	
	[STATE_GOTO_HOME_UP] = {
		COMMUTE_RULE(-1, STATE_GOTO_HOME_UP, SYM_AT, +1, STATE_GOTO_TALLY_END_UP)
	},
	[STATE_GOTO_TALLY_END_UP] = {
		[SYM_T] = {SYM_T, +1, STATE_GOTO_TALLY_END_UP},
		[SYM_PERIOD] = {SYM_T, +1, STATE_RETURN_TO_GRID_UP},
		[SYM_E] = {SYM_E, -1, STATE_GOTO_HOME_FOR_RESET_UP},
	},
	[STATE_RETURN_TO_GRID_UP] = {
		COMMUTE_RULE(+1, STATE_RETURN_TO_GRID_UP, SYM_SH_PERIOD, -1, STATE_MOVE_LEFT_AND_MARK),
		[SYM_SH_PERIOD] = {SYM_PERIOD, -1, STATE_MOVE_LEFT_AND_MARK},
		[SYM_SH_HASH]   = {SYM_HASH,   -1, STATE_MOVE_LEFT_AND_MARK},
		[SYM_SH_X]      = {SYM_X,      -1, STATE_MOVE_LEFT_AND_MARK},
		[SYM_SH_R]      = {SYM_R,      -1, STATE_MOVE_LEFT_AND_MARK},
	},
	[STATE_MOVE_LEFT_AND_MARK] = {
		[SYM_PERIOD]    = {SYM_SH_PERIOD, -1, STATE_GOTO_HOME_UP},
		[SYM_HASH]      = {SYM_SH_HASH,   -1, STATE_GOTO_HOME_UP},
		[SYM_X]         = {SYM_SH_X,      -1, STATE_GOTO_HOME_UP},
		[SYM_R]         = {SYM_SH_R,      -1, STATE_GOTO_HOME_UP}, /* BUG FIX */
	},
	[STATE_GOTO_HOME_FOR_RESET_UP] = {
		COMMUTE_RULE(-1, STATE_GOTO_HOME_FOR_RESET_UP, SYM_AT, +1, STATE_RESET_TALLY_UP)
	},
	[STATE_RESET_TALLY_UP] = {
		[SYM_T] = {SYM_PERIOD, +1, STATE_RESET_TALLY_UP},
		[SYM_E] = {SYM_E, +1, STATE_GOTO_FINAL_POS_UP},
	},
	[STATE_GOTO_FINAL_POS_UP] = {
		COMMUTE_RULE(+1, STATE_GOTO_FINAL_POS_UP, SYM_SH_PERIOD, 0, STATE_RESPOND_UP),
		[SYM_SH_PERIOD] = {SYM_PERIOD, 0, STATE_RESPOND_UP},
		[SYM_SH_HASH]   = {SYM_HASH,   0, STATE_RESPOND_UP},
		[SYM_SH_X]      = {SYM_X,      0, STATE_RESPOND_UP},
		[SYM_SH_R]      = {SYM_R,      0, STATE_RESPOND_UP},
	},

	/* --- 3. SUBROUTINE: GO_DOWN (pos + NCOLS) --- */
	
	[STATE_GOTO_HOME_DOWN] = {
		COMMUTE_RULE(-1, STATE_GOTO_HOME_DOWN, SYM_AT, +1, STATE_GOTO_TALLY_END_DOWN)
	},
	[STATE_GOTO_TALLY_END_DOWN] = {
		[SYM_T] = {SYM_T, +1, STATE_GOTO_TALLY_END_DOWN},
		[SYM_PERIOD] = {SYM_T, +1, STATE_RETURN_TO_GRID_DOWN},
		[SYM_E] = {SYM_E, -1, STATE_GOTO_HOME_FOR_RESET_DOWN},
	},
	[STATE_RETURN_TO_GRID_DOWN] = {
		COMMUTE_RULE(+1, STATE_RETURN_TO_GRID_DOWN, SYM_SH_PERIOD, +1, STATE_MOVE_RIGHT_AND_MARK),
		[SYM_SH_PERIOD] = {SYM_PERIOD, +1, STATE_MOVE_RIGHT_AND_MARK},
		[SYM_SH_HASH]   = {SYM_HASH,   +1, STATE_MOVE_RIGHT_AND_MARK},
		[SYM_SH_X]      = {SYM_X,      +1, STATE_MOVE_RIGHT_AND_MARK},
		[SYM_SH_R]      = {SYM_R,      +1, STATE_MOVE_RIGHT_AND_MARK},
	},
	[STATE_MOVE_RIGHT_AND_MARK] = {
		[SYM_PERIOD]    = {SYM_SH_PERIOD, -1, STATE_GOTO_HOME_DOWN},
		[SYM_HASH]      = {SYM_SH_HASH,   -1, STATE_GOTO_HOME_DOWN},
		[SYM_X]         = {SYM_SH_X,      -1, STATE_GOTO_HOME_DOWN},
		[SYM_R]         = {SYM_SH_R,      -1, STATE_GOTO_HOME_DOWN}, /* BUG FIX */
	},
	[STATE_GOTO_HOME_FOR_RESET_DOWN] = {
		COMMUTE_RULE(-1, STATE_GOTO_HOME_FOR_RESET_DOWN, SYM_AT, +1, STATE_RESET_TALLY_DOWN)
	},
	[STATE_RESET_TALLY_DOWN] = {
		[SYM_T] = {SYM_PERIOD, +1, STATE_RESET_TALLY_DOWN},
		[SYM_E] = {SYM_E, +1, STATE_GOTO_FINAL_POS_DOWN},
	},
	[STATE_GOTO_FINAL_POS_DOWN] = {
		COMMUTE_RULE(+1, STATE_GOTO_FINAL_POS_DOWN, SYM_SH_PERIOD, 0, STATE_RESPOND_DOWN),
		[SYM_SH_PERIOD] = {SYM_PERIOD, 0, STATE_RESPOND_DOWN},
		[SYM_SH_HASH]   = {SYM_HASH,   0, STATE_RESPOND_DOWN},
		[SYM_SH_X]      = {SYM_X,      0, STATE_RESPOND_DOWN},
		[SYM_SH_R]      = {SYM_R,      0, STATE_RESPOND_DOWN},
	},
	
	/* --- 4. SUBROUTINE: GO_UP_RETURN (pos - NCOLS) --- */
	
	[STATE_GOTO_HOME_UP_RETURN] = {
		COMMUTE_RULE(-1, STATE_GOTO_HOME_UP_RETURN, SYM_AT, +1, STATE_GOTO_TALLY_END_UP_RETURN)
	},
	[STATE_GOTO_TALLY_END_UP_RETURN] = {
		[SYM_T] = {SYM_T, +1, STATE_GOTO_TALLY_END_UP_RETURN},
		[SYM_PERIOD] = {SYM_T, +1, STATE_RETURN_TO_GRID_UP_RETURN},
		[SYM_E] = {SYM_E, -1, STATE_GOTO_HOME_FOR_RESET_UP_RETURN},
	},
	[STATE_RETURN_TO_GRID_UP_RETURN] = {
		COMMUTE_RULE(+1, STATE_RETURN_TO_GRID_UP_RETURN, SYM_SH_HASH, -1, STATE_MOVE_LEFT_AND_MARK_RETURN),
		[SYM_SH_PERIOD] = {SYM_PERIOD, -1, STATE_MOVE_LEFT_AND_MARK_RETURN},
		[SYM_SH_HASH]   = {SYM_HASH,   -1, STATE_MOVE_LEFT_AND_MARK_RETURN},
		[SYM_SH_X]      = {SYM_X,      -1, STATE_MOVE_LEFT_AND_MARK_RETURN},
		[SYM_SH_R]      = {SYM_R,      -1, STATE_MOVE_LEFT_AND_MARK_RETURN},
	},
	[STATE_MOVE_LEFT_AND_MARK_RETURN] = {
		[SYM_PERIOD] = {SYM_SH_PERIOD, -1, STATE_GOTO_HOME_UP_RETURN},
		[SYM_HASH]   = {SYM_SH_HASH,   -1, STATE_GOTO_HOME_UP_RETURN},
		[SYM_X]      = {SYM_SH_X,      -1, STATE_GOTO_HOME_UP_RETURN},
		[SYM_R]      = {SYM_SH_R,      -1, STATE_GOTO_HOME_UP_RETURN}, /* BUG FIX */
	},
	[STATE_GOTO_HOME_FOR_RESET_UP_RETURN] = {
		COMMUTE_RULE(-1, STATE_GOTO_HOME_FOR_RESET_UP_RETURN, SYM_AT, +1, STATE_RESET_TALLY_UP_RETURN)
	},
	[STATE_RESET_TALLY_UP_RETURN] = {
		[SYM_T] = {SYM_PERIOD, +1, STATE_RESET_TALLY_UP_RETURN},
		[SYM_E] = {SYM_E, +1, STATE_GOTO_FINAL_POS_UP_RETURN},
	},
	[STATE_GOTO_FINAL_POS_UP_RETURN] = {
		COMMUTE_RULE(+1, STATE_GOTO_FINAL_POS_UP_RETURN, SYM_SH_HASH, 0, STATE_QUERY_LEFT),
		[SYM_SH_PERIOD] = {SYM_PERIOD, 0, STATE_QUERY_LEFT},
		[SYM_SH_HASH]   = {SYM_HASH,   0, STATE_QUERY_LEFT},
		[SYM_SH_X]      = {SYM_X,      0, STATE_QUERY_LEFT},
		[SYM_SH_R]      = {SYM_R,      0, STATE_QUERY_LEFT},
	},
	
	/* --- 5. SUBROUTINE: GO_DOWN_RETURN (pos + NCOLS) --- */
	
	[STATE_GOTO_HOME_DOWN_RETURN] = {
		COMMUTE_RULE(-1, STATE_GOTO_HOME_DOWN_RETURN, SYM_AT, +1, STATE_GOTO_TALLY_END_DOWN_RETURN)
	},
	[STATE_GOTO_TALLY_END_DOWN_RETURN] = {
		[SYM_T] = {SYM_T, +1, STATE_GOTO_TALLY_END_DOWN_RETURN},
		[SYM_PERIOD] = {SYM_T, +1, STATE_RETURN_TO_GRID_DOWN_RETURN},
		[SYM_E] = {SYM_E, -1, STATE_GOTO_HOME_FOR_RESET_DOWN_RETURN},
	},
	[STATE_RETURN_TO_GRID_DOWN_RETURN] = {
		COMMUTE_RULE(+1, STATE_RETURN_TO_GRID_DOWN_RETURN, SYM_SH_HASH, +1, STATE_MOVE_RIGHT_AND_MARK_RETURN),
		[SYM_SH_PERIOD] = {SYM_PERIOD, +1, STATE_MOVE_RIGHT_AND_MARK_RETURN},
		[SYM_SH_HASH]   = {SYM_HASH,   +1, STATE_MOVE_RIGHT_AND_MARK_RETURN},
		[SYM_SH_X]      = {SYM_X,      +1, STATE_MOVE_RIGHT_AND_MARK_RETURN},
		[SYM_SH_R]      = {SYM_R,      +1, STATE_MOVE_RIGHT_AND_MARK_RETURN},
	},
	[STATE_MOVE_RIGHT_AND_MARK_RETURN] = {
		[SYM_PERIOD] = {SYM_SH_PERIOD, -1, STATE_GOTO_HOME_DOWN_RETURN},
		[SYM_HASH]   = {SYM_SH_HASH,   -1, STATE_GOTO_HOME_DOWN_RETURN},
		[SYM_X]      = {SYM_SH_X,      -1, STATE_GOTO_HOME_DOWN_RETURN},
		[SYM_R]      = {SYM_SH_R,      -1, STATE_GOTO_HOME_DOWN_RETURN}, /* BUG FIX */
	},
	[STATE_GOTO_HOME_FOR_RESET_DOWN_RETURN] = {
		COMMUTE_RULE(-1, STATE_GOTO_HOME_FOR_RESET_DOWN_RETURN, SYM_AT, +1, STATE_RESET_TALLY_DOWN_RETURN)
	},
	[STATE_RESET_TALLY_DOWN_RETURN] = {
		[SYM_T] = {SYM_PERIOD, +1, STATE_RESET_TALLY_DOWN_RETURN},
		[SYM_E] = {SYM_E, +1, STATE_GOTO_FINAL_POS_DOWN_RETURN},
	},
	[STATE_GOTO_FINAL_POS_DOWN_RETURN] = {
		COMMUTE_RULE(+1, STATE_GOTO_FINAL_POS_DOWN_RETURN, SYM_SH_HASH, 0, STATE_QUERY_RIGHT),
		[SYM_SH_PERIOD] = {SYM_PERIOD, 0, STATE_QUERY_RIGHT},
		[SYM_SH_HASH]   = {SYM_HASH,   0, STATE_QUERY_RIGHT},
		[SYM_SH_X]      = {SYM_X,      0, STATE_QUERY_RIGHT},
		[SYM_SH_R]      = {SYM_R,      0, STATE_QUERY_RIGHT},
	},
};

#endif /* MACHINE2_H_ */

